### PR TITLE
Create LATEST_BETA

### PR DESCRIPTION
**Pull request by JohanEngelen**
Similar to DMD's http://ftp.digitalmars.com/LATEST_BETA

https://forum.dlang.org/post/doghiutddqbvutpxtkyf@forum.dlang.org

### CODE REVIEW

**Comment by JohanEngelen** [comment]
(I can't commit to this repo)

**Comment by dnadlinger** [comment]
> (I can't commit to this repo)

Should be fixed.

**Comment by dnadlinger** [comment]
Note that creating the file itself doesn't enable anything; support still needs to be added to @MartinNowak's `install.sh`.

**Comment by JohanEngelen** [comment]
Yep, but didn't want to submit a PR before the file exists.

**Comment by JohanEngelen** [comment]
https://github.com/dlang/installer/pull/186

**Pull request merged**
